
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 11 19:54:26 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 12;
  public static final int CHAR = 3;
  public static final int GREATEQUAL = 31;
  public static final int EQUALS = 36;
  public static final int GREAT = 30;
  public static final int TWOTACKS = 40;
  public static final int REM = 27;
  public static final int NOTEQUAL = 29;
  public static final int LPAREN = 43;
  public static final int SEMI = 39;
  public static final int CONTINUE = 21;
  public static final int LESS = 32;
  public static final int MINUS = 24;
  public static final int RPAREN = 44;
  public static final int IMPLICATION = 49;
  public static final int AND = 34;
  public static final int LESSEQUAL = 33;
  public static final int OR = 35;
  public static final int COMMA = 41;
  public static final int BOOL = 4;
  public static final int CLASS = 10;
  public static final int INC = 37;
  public static final int DIV = 26;
  public static final int PLUS = 23;
  public static final int IF = 6;
  public static final int DOT = 42;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int EQUAL = 28;
  public static final int NEW = 15;
  public static final int error = 1;
  public static final int PROGRAM = 8;
  public static final int MUL = 25;
  public static final int NUMBER = 2;
  public static final int BREAK = 9;
  public static final int IDENT = 5;
  public static final int VOID = 19;
  public static final int LBRACK = 45;
  public static final int FOREACH = 22;
  public static final int LBRACE = 47;
  public static final int ELSE = 7;
  public static final int RBRACK = 46;
  public static final int ENUM = 11;
  public static final int READ = 17;
  public static final int WHILE = 14;
  public static final int RBRACE = 48;
  public static final int EXTENDS = 20;
  public static final int DEC = 38;
  public static final int PRINT = 16;
  public static final int DO = 13;
}

